name: Run PySpark Code

on:
  workflow_dispatch:
    inputs:
      scriptPath:
        description: 'Relative path to PySpark script file'
        required: true
    # inputs:
    #   sparkVersions:
    #     description: 'JSON array of Spark versions'
    #     required: true
    #     default: '["2.0.0", "3.0.0"]'
    # tags:
    #   description: 'Some tag'

jobs:
  run-on-spark:
    name: Run PySpark code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run sample Python code
        shell: python
        run: |
          from polyspark import run_on_spark
          run_on_spark('${{ github.event.inputs.scriptPath }}', '2.0.0')
      #   continue-on-error: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
